language: c
sudo: false
before_install:
  - ./install-pgi.sh
matrix:
  include:
    - dist: bionic
    - dist: xenial
    - dist: trusty
    - dist: precise
script:
  - pgcc -dM -E /dev/null
notifications:
  email:
    on_success: never
    on_failure: never
